server.port=8081
server.address=0.0.0.0
spring.application.name=orquestador-service

# Dirección de la Máquina 3 (Balanceador de Carga, puerto 8080)
balanceador.url=http://127.0.0.1:8080/  ### Cambia 127.0.0.1 por la IP de la PC B

# Parametros del Circuit Breaker
circuitbreaker.umbral-fallos=3
circuitbreaker.tiempo-half-open=10
http.timeout=2000
