server.port=8081
server.address=0.0.0.0
spring.application.name=orquestador-service

balanceador.url=http://127.0.0.1:8080/

# Parametros del Circuit Breaker
circuitbreaker.umbral-fallos=3
circuitbreaker.tiempo-half-open=10
http.timeout=2000
