server.port=8080
server.address=0.0.0.0
spring.application.name=balanceador-service

# Base de datos SQLite
spring.datasource.url=jdbc:sqlite:nodos.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Nodos (valores por defecto para localhost)
# IP del Nodo de Pagos 1 (Máquina 192.168.1.14, puerto 9001)
pagos1.url=http://192.168.1.14:9001/
# IP del Nodo de Pagos 2 (Máquina 192.168.1.10, puerto 9002)
pagos2.url=http://192.168.1.10:9002/
 
# Tiempos (ms)
heartbeat.interval=1000
heartbeat.timeout=1000
http.timeout=2000
